server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.108.29.69:40155/smartdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&useSSL=false&allowMultiQueries=true
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  elasticsearch:
    rest:
      uris: 47.108.133.131:9200

mybatis:
  type-aliases-package: com.bz
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
